# Sesión 5 · pandas: Series y DataFrame

**Fundamentos de Ciencia de Datos e IA (CDIAG1003)** · Semana 3, sesión 5 · Notebook de clase (sin nota)

En la sesión 4 se trabajó con arrays de NumPy: valores de un solo tipo, que se eligen por **posición**. Hoy se añade lo que le falta a un array para representar una tabla de datos real: **etiquetas** en las filas y en las columnas, y **un tipo de dato por columna**. Eso es pandas.

Este notebook funciona igual que el de la sesión 4:

- **celdas de demostración**, ya escritas: ejecútelas con **Shift + Enter** y observe el resultado;
- ejercicios cortos **«Su turno»**, con una celda `# TODO` y un `assert` debajo que comprueba la respuesta. Si la celda del `assert` no muestra un error, la respuesta es correcta.

En cada `# TODO`, reemplace los tres puntos (`...`) por su código. Un error que menciona `ellipsis` indica que quedó un `...` sin reemplazar.

| Sección | Tema | Lectura |
|---|---|---|
| 1 | De NumPy a pandas: por qué hacen falta etiquetas | McKinney cap. 5 (introducción) |
| 2 | `Series`: un array con etiquetas | McKinney §5.1 «Series» · VanderPlas cap. 3 «The Pandas Series Object» |
| 3 | `DataFrame`: leer un archivo e inspeccionarlo | McKinney §5.1 «DataFrame» · §6.1 (`read_csv`) |
| 4 | Columnas: seleccionar y crear | McKinney §5.1 «DataFrame» |
| 5 | Filas: `loc` e `iloc` | McKinney §5.2 «Selección en dataframes con loc e iloc» |
| 6 | Condiciones | McKinney §5.2 «Indexación, selección y filtrado» · VanderPlas «Data Indexing and Selection» |
| 7 | Tipos de datos y regreso a NumPy | McKinney §5.1 · §7.2 (`astype`) |
| 8 | Cierre: el reto del Notebook 0, tercera versión | — |

> Si algo deja de funcionar, use el menú *Kernel → Restart Kernel* y vuelva a ejecutar las celdas desde el inicio (*Run → Run All Above Selected Cell*).

In [2]:
import numpy as np
import pandas as pd      # por convención, pandas siempre se importa con el alias pd

print("NumPy", np.__version__, "| pandas", pd.__version__)

NumPy 2.4.6 | pandas 3.0.3

> **Nota sobre las versiones.** Este notebook funciona con pandas 2 y con pandas 3. La diferencia visible está en las columnas de **texto**: pandas 3 muestra su tipo como `str`; pandas 2 (y el libro de McKinney), como `object`. Los dos nombres indican lo mismo: «esta columna contiene texto».

## 1. De NumPy a pandas: por qué hacen falta etiquetas

Estos son los datos de la sesión 4: las notas de seis estudiantes en tres evaluaciones.

In [3]:
nombres = np.array(["Ana", "Luis", "María", "Jorge", "Camila", "Diego"])
notas = np.array([[85, 90, 78],
                  [70, 65, 80],
                  [95, 92, 98],
                  [55, 60, 58],
                  [88, 79, 91],
                  [62, 74, 69]])

notas[4, 2]     # ¿de quién es esta nota y de qué evaluación? El array no lo dice

np.int64(91)

Con un array hay que **recordar** que la fila 4 es Camila y que la columna 2 es la tercera evaluación. Además, los nombres viven en otro array, porque un array solo admite un tipo de dato.

Un **DataFrame** de pandas guarda la misma matriz junto con sus etiquetas: un **índice** (*index*) para las filas y un nombre para cada **columna**.

In [4]:
df_notas = pd.DataFrame(notas, index=nombres, columns=["ev1", "ev2", "ev3"])
df_notas

        ev1  ev2  ev3
Ana      85   90   78
Luis     70   65   80
María    95   92   98
Jorge    55   60   58
Camila   88   79   91
Diego    62   74   69

In [5]:
df_notas.loc["Camila", "ev3"]     # la misma nota, ahora pedida por sus etiquetas

np.int64(91)

In [6]:
print(df_notas.shape)      # (filas, columnas), igual que en NumPy
print(df_notas.index)      # las etiquetas de las filas
print(df_notas.columns)    # las etiquetas de las columnas

(6, 3)
Index(['Ana', 'Luis', 'María', 'Jorge', 'Camila', 'Diego'], dtype='str')
Index(['ev1', 'ev2', 'ev3'], dtype='str')

| | Array de NumPy | DataFrame de pandas |
|---|---|---|
| Se eligen los datos por… | posición: `notas[4, 2]` | etiqueta: `df_notas.loc["Camila", "ev3"]` (y también por posición) |
| Tipos de datos | uno solo para todo el array | uno por columna |
| Sirve para… | cálculo numérico con matrices | tablas de datos: archivos CSV, Excel, bases de datos |

pandas está construido sobre NumPy: cada columna guarda sus valores en un array, y lo aprendido en la sesión 4 (operaciones vectorizadas, máscaras, agregaciones) funciona igual.

**Su turno 1.1.** Con el array `precios`, cree el DataFrame `df_precios`: el índice son los tres productos y las columnas se llaman `"precio_2025"` y `"precio_2026"`. Después, guarde en `cafe_2026` el precio del café en 2026, pedido por sus etiquetas con `.loc`.

In [7]:
precios = np.array([[1.7, 1.8],
                    [6.0, 6.5],
                    [3.0, 3.2]])
productos = ["Galletas", "Café", "Chocolate"]

# TODO: reemplace los ... por su código
df_precios = pd.DataFrame(precios, index=productos, columns=["precio_2025", "precio_2026"])
cafe_2026 = df_precios.loc["Café", "precio_2026"]
df_precios

           precio_2025  precio_2026
Galletas           1.7          1.8
Café               6.0          6.5
Chocolate          3.0          3.2

## 2. `Series`: un array con etiquetas

Una **columna** de un DataFrame es una **Series**: un array de una dimensión en el que cada valor tiene una etiqueta.

In [8]:
ev1 = df_notas["ev1"]        # una columna del DataFrame
print(type(ev1))
ev1

<class 'pandas.Series'>

Ana       85
Luis      70
María     95
Jorge     55
Camila    88
Diego     62
Name: ev1, dtype: int64

In [9]:
print(ev1.to_numpy())    # los valores: un array de NumPy
print(ev1.index)         # las etiquetas
print(ev1.name, "|", ev1.dtype, "|", ev1.shape)

[85 70 95 55 88 62]
Index(['Ana', 'Luis', 'María', 'Jorge', 'Camila', 'Diego'], dtype='str')
ev1 | int64 | (6,)

Una Series también se crea directamente, con una lista y un índice, o con un diccionario (las claves pasan a ser las etiquetas).

In [10]:
edades = pd.Series([19, 21, 20], index=["Ana", "Luis", "María"], name="edad")
ciudad_origen = pd.Series({"Ana": "Guayaquil", "Luis": "Quito", "María": "Cuenca"})
print(edades)
print(ciudad_origen)

Ana      19
Luis     21
María    20
Name: edad, dtype: int64
Ana      Guayaquil
Luis         Quito
María       Cuenca
dtype: str

**Elegir valores.** Por etiqueta se usan corchetes o `.loc`; por posición, `.iloc`.

In [11]:
print(ev1["María"])                 # por etiqueta
print(ev1.iloc[2])                  # por posición (la tercera)
print(ev1[["Ana", "Jorge"]])        # varias etiquetas: una lista dentro de los corchetes
print(ev1["Luis":"Jorge"])          # slice por etiquetas: el fin SÍ se incluye

95
95
Ana      85
Jorge    55
Name: ev1, dtype: int64
Luis     70
María    95
Jorge    55
Name: ev1, dtype: int64

> **Atención.** Con un índice de texto, `ev1[2]` no es una forma segura de pedir «el tercer valor»: en pandas 3 produce un error (`KeyError`), porque el número 2 no es una etiqueta. Para pedir por posición se usa siempre `.iloc`.

**Todo lo de NumPy sigue funcionando**: operaciones vectorizadas, comparaciones, máscaras y agregaciones. La diferencia es que el resultado conserva las etiquetas.

In [12]:
print(ev1 + 5)                      # operación vectorizada: conserva las etiquetas
print(ev1[ev1 >= 80])               # máscara booleana, como en NumPy
print(ev1.mean(), ev1.max(), (ev1 >= 60).sum())
print(ev1.idxmax())                 # como argmax, pero devuelve la ETIQUETA del máximo

Ana        90
Luis       75
María     100
Jorge      60
Camila     93
Diego      67
Name: ev1, dtype: int64
Ana       85
María     95
Camila    88
Name: ev1, dtype: int64
75.83333333333333 95 5
María

**Las operaciones entre dos Series se alinean por etiqueta, no por posición.** Si una etiqueta falta en una de las dos, el resultado es `NaN` (*not a number*): el valor que pandas usa para un dato faltante. Los datos faltantes se estudian en la sesión 7.

In [13]:
bono = pd.Series({"Diego": 5, "Ana": 10})    # solo dos estudiantes, y en otro orden
ev1 + bono

Ana       95.0
Camila     NaN
Diego     67.0
Jorge      NaN
Luis       NaN
María      NaN
dtype: float64

**Su turno 2.1.** La Series `unidades` contiene las unidades vendidas de cada producto de la tienda entre enero y marzo. Obtenga:

- `mas_vendido`: el **nombre** del producto con más unidades;
- `sobre_65`: una Series con los productos que vendieron más de 65 unidades;
- `total_unidades`: la suma de todas las unidades.

In [14]:
unidades = pd.Series({"Audífonos": 66, "Bolígrafo": 61, "Café": 70, "Cargador": 75, "Chocolate": 64,
                      "Cuaderno": 63, "Galletas": 73, "Licuadora": 40, "Mouse": 54, "Sartén": 69}, name = "unidades")

# TODO: reemplace los ... por su código
mas_vendido = unidades.idxmax()
sobre_65 = unidades[unidades > 65]
total_unidades = unidades.sum()
print(mas_vendido, total_unidades)
print(sobre_65)

Cargador 635
Audífonos    66
Café         70
Cargador     75
Galletas     73
Sartén       69
Name: unidades, dtype: int64

In [15]:
assert mas_vendido == "Cargador", "idxmax devuelve la etiqueta del valor más alto"
assert isinstance(sobre_65, pd.Series) and set(sobre_65.index) == {"Audífonos", "Café", "Cargador", "Galletas", "Sartén"}, "Filtre con la máscara unidades > 65"
assert total_unidades == 635, "Sume la Series con .sum()"

## 3. `DataFrame`: leer un archivo e inspeccionarlo

En la sesión 4, cada columna de `ventas_tienda.csv` se leyó por separado con `np.loadtxt`, porque un array tiene un solo tipo. `pd.read_csv` lee **todo el archivo** en una línea: usa la primera fila como nombres de columna y decide el tipo de cada columna.

In [16]:
ventas = pd.read_csv("datos/ventas_tienda.csv")
ventas.head()          # las cinco primeras filas; head(10) muestra diez

        fecha  producto    categoria  cantidad  precio_unitario     ciudad
0  2026-01-02    Sartén        Hogar         1             18.0      Quito
1  2026-01-02     Mouse  Electrónica         1             15.0    Machala
2  2026-01-03  Galletas    Alimentos         2              1.8      Quito
3  2026-01-03  Cuaderno    Papelería         2              2.5  Guayaquil
4  2026-01-04  Cargador  Electrónica         3             12.5  Guayaquil

> Si aparece `FileNotFoundError`, Jupyter se abrió en otra carpeta. Ejecute `import os; print(os.getcwd())` para ver la carpeta actual; el notebook debe estar junto a la carpeta `datos`.

La columna sin nombre de la izquierda (0, 1, 2, …) es el **índice**: como el archivo no trae etiquetas de fila, pandas numera las filas desde 0.

Lo primero que se hace con un conjunto de datos nuevo es **inspeccionarlo**:

In [17]:
print(ventas.shape)        # (filas, columnas)
print(ventas.columns)      # nombres de las columnas
ventas.tail(3)             # las tres últimas filas

(200, 6)
Index(['fecha', 'producto', 'categoria', 'cantidad', 'precio_unitario',
       'ciudad'],
      dtype='str')

          fecha   producto    categoria  cantidad  precio_unitario  ciudad
197  2026-03-31  Audífonos  Electrónica         2             25.0   Quito
198  2026-03-31  Audífonos  Electrónica         2             25.0  Cuenca
199  2026-03-31   Galletas    Alimentos         1              1.8   Quito

In [18]:
ventas.dtypes              # el tipo de cada columna

fecha                  str
producto               str
categoria              str
cantidad             int64
precio_unitario    float64
ciudad                 str
dtype: object

In [19]:
ventas.info()              # resumen: filas, columnas, valores no nulos y tipos

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            200 non-null    str
 1   producto         200 non-null    str
 2   categoria        200 non-null    str
 3   cantidad         200 non-null    int64
 4   precio_unitario  200 non-null    float64
 5   ciudad           200 non-null    str
dtypes: float64(1), int64(1), str(4)
memory usage: 16.1 KB

In [20]:
ventas.describe()          # estadísticas de las columnas numéricas

        cantidad  precio_unitario
count  200.00000       200.000000
mean     3.17500        12.173500
std      2.44217        12.032767
min      1.00000         0.600000
25%      1.00000         2.500000
50%      2.00000         9.500000
75%      5.00000        18.000000
max     10.00000        45.000000

Lectura de `dtypes`, con la tabla de tipos de la sesión 3:

| Columna | Tipo en pandas | Tipo de dato (sesión 3) |
|---|---|---|
| `cantidad` | `int64` | numérico discreto |
| `precio_unitario` | `float64` | numérico continuo |
| `producto`, `categoria`, `ciudad` | `str` (pandas 3) u `object` (pandas 2) | categórico nominal |
| `fecha` | `str` u `object`: se leyó como **texto** | fecha (se convierte en la sección 7) |

**Su turno 3.1.** Guarde en `n_filas` y `n_columnas` el número de filas y de columnas de `ventas` (use `.shape`), en `precio_max` el precio unitario más alto y en `cantidad_media` la cantidad promedio por venta.

In [21]:
# TODO: reemplace los ... por su código
n_filas = ventas.shape[0]
n_columnas = ventas.shape[1]
precio_max = ventas["precio_unitario"].max()
cantidad_media = ventas["cantidad"].mean()
print(n_filas, n_columnas, precio_max, cantidad_media)

200 6 45.0 3.175

In [22]:
assert n_filas == 200 and n_columnas == 6, "ventas.shape es una tupla (filas, columnas)"
assert precio_max == 45.0, "Seleccione la columna precio_unitario y use .max()"
assert round(float(cantidad_media), 3) == 3.175, "Seleccione la columna cantidad y use .mean()"

## 4. Columnas: seleccionar y crear

- `df["columna"]` → una **Series**.
- `df[["col1", "col2"]]` → un **DataFrame** con esas columnas. Los corchetes dobles son una **lista** de nombres dentro de los corchetes de selección.

In [23]:
ciudad = ventas["ciudad"]                       # Series
parte = ventas[["producto", "ciudad"]]          # DataFrame
print(type(ciudad).__name__, ciudad.shape)
print(type(parte).__name__, parte.shape)
parte.head(3)

Series (200,)
DataFrame (200, 2)

   producto   ciudad
0    Sartén    Quito
1     Mouse  Machala
2  Galletas    Quito

**Crear una columna** es asignarle un valor a un nombre nuevo. La operación es vectorizada: se calcula para las 200 filas a la vez, como `cantidad * precio` en NumPy.

In [24]:
ventas["ingreso"] = ventas["cantidad"] * ventas["precio_unitario"]
ventas.head(3)

,fecha,producto,categoria,cantidad,precio_unitario,ciudad,ingreso
0,2026-01-02,Sartén,Hogar,1,18.0,Quito,18.0
1,2026-01-02,Mouse,Electrónica,1,15.0,Machala,15.0
2,2026-01-03,Galletas,Alimentos,2,1.8,Quito,3.6

In [25]:
print("Ingreso total:", ventas["ingreso"].sum().round(2))        # 7424.8, como en el Taller 1
print("Ticket promedio:", ventas["ingreso"].mean().round(2))     # 37.12

Ingreso total: 7424.8
Ticket promedio: 37.12

Tres métodos muy usados para conocer una columna:

In [26]:
print(ventas["categoria"].unique())             # los valores distintos
print(ventas["producto"].nunique())             # cuántos valores distintos hay
ventas["ciudad"].value_counts()                 # cuántas filas tiene cada valor, de mayor a menor

<ArrowStringArray>
['Hogar', 'Electrónica', 'Alimentos', 'Papelería']
Length: 4, dtype: str
10

ciudad
Guayaquil    76
Quito        60
Cuenca       36
Manta        16
Machala      12
Name: count, dtype: int64

In [27]:
ventas.sort_values("ingreso", ascending=False).head(3)    # las tres ventas de mayor ingreso

,fecha,producto,categoria,cantidad,precio_unitario,ciudad,ingreso
57,2026-01-28,Licuadora,Hogar,6,45.0,Guayaquil,270.0
188,2026-03-28,Audífonos,Electrónica,10,25.0,Quito,250.0
72,2026-02-07,Licuadora,Hogar,5,45.0,Guayaquil,225.0

`sort_values` devuelve una tabla **nueva** y ordenada; `ventas` no cambia. Observe el índice del resultado: cada fila conserva su etiqueta original (las dos primeras son 57 y 188). Cuando dos filas tienen el mismo valor, su orden relativo puede cambiar de una versión de pandas a otra.

**Su turno 4.1.** (a) Cree la columna `ingreso_neto`: el ingreso con un descuento del 10 %. (b) Guarde en `ventas_por_ciudad` el número de ventas de cada ciudad. (c) Guarde en `n_productos` cuántos productos distintos hay.

In [37]:
# TODO: reemplace los ... por su código
ventas["ingreso_neto"] =  ventas["ingreso"] - (ventas["ingreso"] * 0.10)
ventas_por_ciudad = ventas["ciudad"].value_counts()
n_productos = ventas["producto"].nunique()
print(ventas_por_ciudad)
print(n_productos)

ciudad
Guayaquil    76
Quito        60
Cuenca       36
Manta        16
Machala      12
Name: count, dtype: int64
10

In [38]:
assert "ingreso_neto" in ventas.columns and ventas["ingreso_neto"].dtype == float, "Cree la columna con ventas['ingreso'] * 0.9"
assert round(float(ventas["ingreso_neto"].sum()), 2) == 6682.32, "El ingreso neto es el 90 % del ingreso"
assert ventas_por_ciudad["Guayaquil"] == 76 and ventas_por_ciudad["Machala"] == 12, "Use value_counts sobre la columna ciudad"
assert n_productos == 10, "Use nunique sobre la columna producto"

## 5. Filas: `loc` e `iloc`

Hay dos formas de elegir filas (y columnas), y conviene no mezclarlas:

| | Elige por… | En un *slice*, el fin… | Ejemplo |
|---|---|---|---|
| `df.iloc[filas, columnas]` | **posición** (enteros desde 0), como NumPy | **no** se incluye | `ventas.iloc[0:3, [1, 4]]` |
| `df.loc[filas, columnas]` | **etiqueta** (del índice y de las columnas) | **sí** se incluye | `ventas.loc[0:3, ["producto", "ingreso"]]` |

Con `df_notas` la diferencia se ve bien, porque las etiquetas de las filas son nombres:

In [39]:
print(df_notas.loc["María"])                        # la fila con etiqueta "María" → Series
print(df_notas.iloc[2])                             # la fila en la posición 2: la misma

ev1    95
ev2    92
ev3    98
Name: María, dtype: int64
ev1    95
ev2    92
ev3    98
Name: María, dtype: int64

In [40]:
print(df_notas.loc["Luis":"Jorge", "ev1":"ev2"])    # por etiquetas: incluye a Jorge y a ev2
print(df_notas.iloc[1:4, 0:2])                      # por posiciones: el 4 y el 2 quedan fuera

       ev1  ev2
Luis    70   65
María   95   92
Jorge   55   60
       ev1  ev2
Luis    70   65
María   95   92
Jorge   55   60

En `ventas`, las etiquetas de las filas son los números 0, 1, 2, …, y por eso `loc` e `iloc` **parecen** iguales. No lo son:

In [41]:
print(len(ventas.iloc[0:3]), "filas con iloc[0:3]")     # posiciones 0, 1 y 2
print(len(ventas.loc[0:3]), "filas con loc[0:3]")       # etiquetas 0, 1, 2 y 3
ventas.loc[0:3, ["producto", "ingreso"]]

3 filas con iloc[0:3]
4 filas con loc[0:3]

   producto  ingreso
0    Sartén     18.0
1     Mouse     15.0
2  Galletas      3.6
3  Cuaderno      5.0

La diferencia importa en cuanto la tabla se **ordena** o se **filtra**: las posiciones cambian, las etiquetas no.

In [42]:
orden = ventas.sort_values("ingreso", ascending=False)

print(orden.iloc[0]["producto"], orden.iloc[0]["ingreso"])   # posición 0: la venta de MAYOR ingreso
print(orden.loc[0]["producto"], orden.loc[0]["ingreso"])     # etiqueta 0: la PRIMERA venta del archivo

Licuadora 270.0
Sartén 18.0

Un valor suelto se pide con fila y columna: `ventas.loc[57, "producto"]`.

El índice se puede cambiar: `set_index` convierte una columna en índice, y `reset_index` hace lo contrario.

In [43]:
tabla = df_notas.reset_index()             # el índice pasa a ser una columna llamada "index"
print(tabla.head(2))
print(tabla.set_index("index").head(2))    # y vuelve a ser el índice

  index  ev1  ev2  ev3
0   Ana   85   90   78
1  Luis   70   65   80
       ev1  ev2  ev3
index
Ana     85   90   78
Luis    70   65   80

**Actividad en papel (en parejas, 6 minutos).** La hoja impresa muestra la tabla `mini`: las ocho primeras filas de `ventas`, con cinco columnas. Para cada expresión de la hoja (A a F), marque **en el papel** las celdas que devuelve y escriba la forma del resultado, **sin ejecutar**. Después, compruebe sus respuestas: ejecute la celda siguiente y, debajo, cada expresión en una celda nueva.

In [44]:
mini = ventas.loc[0:7, ["producto", "cantidad", "precio_unitario", "ciudad", "ingreso"]]
mini

   producto  cantidad  precio_unitario     ciudad  ingreso
0    Sartén         1             18.0      Quito     18.0
1     Mouse         1             15.0    Machala     15.0
2  Galletas         2              1.8      Quito      3.6
3  Cuaderno         2              2.5  Guayaquil      5.0
4  Cargador         3             12.5  Guayaquil     37.5
5  Cuaderno         4              2.5  Guayaquil     10.0
6  Galletas         1              1.8  Guayaquil      1.8
7    Sartén         6             18.0  Guayaquil    108.0

**Su turno 5.1.** Obtenga:

- `producto_57`: el producto de la venta con etiqueta 57 (use `.loc` con fila y columna);
- `primeras`: las 5 primeras filas y las 3 primeras columnas de `ventas` (use `.iloc`);
- `bloque`: las columnas `producto` y `ciudad` de las ventas con etiquetas 10, 11 y 12 (use `.loc`);
- `mayor`: la **fila** de la venta de mayor ingreso (ordene de mayor a menor y tome la primera posición).

In [54]:
# TODO: reemplace los ... por su código
producto_57 = ventas.loc[57]["producto"]
primeras = ventas.iloc[:5, :3]
bloque = ventas.loc[10:12, ["producto", "ciudad"]]
mayor = ventas.sort_values("ingreso", ascending=False).iloc[0]
print(producto_57)
print(primeras)
print(bloque)
print(mayor)

Licuadora
        fecha  producto    categoria
0  2026-01-02    Sartén        Hogar
1  2026-01-02     Mouse  Electrónica
2  2026-01-03  Galletas    Alimentos
3  2026-01-03  Cuaderno    Papelería
4  2026-01-04  Cargador  Electrónica
     producto     ciudad
10      Mouse  Guayaquil
11  Bolígrafo     Cuenca
12   Cuaderno  Guayaquil
fecha              2026-01-28
producto            Licuadora
categoria               Hogar
cantidad                    6
precio_unitario          45.0
ciudad              Guayaquil
ingreso                 270.0
ingreso_neto            243.0
Name: 57, dtype: object

In [55]:
assert producto_57 == "Licuadora", "ventas.loc[57, 'producto']"
assert isinstance(primeras, pd.DataFrame) and primeras.shape == (5, 3), "iloc[:5, :3]: 5 filas y 3 columnas"
assert list(primeras.columns) == ["fecha", "producto", "categoria"], "Las tres primeras columnas son fecha, producto y categoria"
assert isinstance(bloque, pd.DataFrame) and bloque.shape == (3, 2), "Con loc, el slice 10:12 incluye la etiqueta 12: son 3 filas"
assert list(bloque["producto"]) == ["Mouse", "Bolígrafo", "Cuaderno"], "Use loc[10:12, ['producto', 'ciudad']]"
assert isinstance(mayor, pd.Series) and mayor["producto"] == "Licuadora" and mayor["ingreso"] == 270.0, "Ordene por ingreso (ascending=False) y use iloc[0]"

## 6. Condiciones

Una comparación sobre una columna devuelve una **Series de `True`/`False`**: una máscara, igual que en NumPy. Con ella se cuenta, se calcula una proporción y se filtran filas.

In [56]:
en_guayaquil = ventas["ciudad"] == "Guayaquil"
print(en_guayaquil.head(4))
print(en_guayaquil.sum(), "ventas en Guayaquil")            # contar: 76
print(en_guayaquil.mean() * 100, "% de las ventas")         # proporción: 38 %

0    False
1    False
2    False
3     True
Name: ciudad, dtype: bool
76 ventas en Guayaquil
38.0 % de las ventas

In [57]:
ventas[en_guayaquil].head(3)                                # filtrar filas: solo las de Guayaquil

,fecha,producto,categoria,cantidad,precio_unitario,ciudad,ingreso,ingreso_neto
3,2026-01-03,Cuaderno,Papelería,2,2.5,Guayaquil,5.0,4.50
4,2026-01-04,Cargador,Electrónica,3,12.5,Guayaquil,37.5,33.75
5,2026-01-04,Cuaderno,Papelería,4,2.5,Guayaquil,10.0,9.00

Con `.loc` se eligen **filas por condición y columnas por nombre** en un solo paso: `df.loc[condición, columnas]`.

In [58]:
ventas.loc[en_guayaquil, ["producto", "ingreso"]].head(3)

   producto  ingreso
3  Cuaderno      5.0
4  Cargador     37.5
5  Cuaderno     10.0

In [59]:
ventas.loc[ventas["categoria"] == "Electrónica", "ingreso"].sum()      # 3397.5, como en el Taller 1

np.float64(3397.5)

Para **combinar condiciones** se usan `&` (y), `|` (o) y `~` (no), **con paréntesis en cada condición**. Igual que con los arrays, `and` y `or` no funcionan.

In [60]:
quito_grandes = (ventas["ciudad"] == "Quito") & (ventas["cantidad"] >= 5)
print(quito_grandes.sum(), ventas.loc[quito_grandes, "ingreso"].sum())     # 16 ventas, 1537.3

# ventas[ventas["ciudad"] == "Quito" and ventas["cantidad"] >= 5]
# ValueError: The truth value of a Series is ambiguous

16 1537.3

Dos métodos ahorran condiciones largas: `isin` (el valor está en una lista) y `between` (el valor está en un intervalo, con los extremos incluidos).

In [61]:
print(ventas["ciudad"].isin(["Cuenca", "Manta"]).sum())           # ventas en Cuenca o en Manta
print(ventas["precio_unitario"].between(10, 20).sum())            # precios de 10 a 20 dólares
print((~ventas["ciudad"].isin(["Guayaquil", "Quito"])).sum())     # ~ niega: ni Guayaquil ni Quito

52
67
64

**Modificar con una condición.** La forma segura es `df.loc[condición, columna] = valor`.

In [ ]:
ventas["tipo"] = "minorista"                                   # un mismo valor para toda la columna
ventas.loc[ventas["cantidad"] >= 5, "tipo"] = "mayorista"      # se cambia solo donde la condición es True
ventas["tipo"].value_counts()

tipo
minorista    149
mayorista     51
Name: count, dtype: int64

> **Atención.** La forma `ventas[ventas["cantidad"] >= 5]["tipo"] = "mayorista"` (dos pares de corchetes seguidos) **no modifica** `ventas`: el primer corchete crea una tabla nueva y el cambio se hace sobre esa tabla temporal. pandas avisa con `SettingWithCopyWarning` (pandas 2) o `ChainedAssignmentError` (pandas 3). Para modificar: siempre un solo `.loc`. Para trabajar con una parte de la tabla como tabla independiente: `parte = ventas[condición].copy()`.

**Su turno 6.1.** Obtenga:

- `electronica`: un DataFrame con las ventas de la categoría `"Electrónica"`;
- `n_grandes`: cuántas ventas tienen un ingreso mayor que 100 dólares;
- `gye_hogar`: el ingreso total de las ventas hechas en Guayaquil **y** de la categoría `"Hogar"`.

In [74]:
# TODO: reemplace los ... por su código
electronica = ventas[ventas["categoria"] == "Electrónica"]
n_grandes = len(ventas[ventas["ingreso"] > 100])
gye_hogar = ventas[(ventas["ciudad"] == "Guayaquil") & (ventas["categoria"] == "Hogar")]["ingreso"].sum()
print(len(electronica), n_grandes, gye_hogar)

64 18 1413.0

In [73]:
assert isinstance(electronica, pd.DataFrame) and len(electronica) == 64, "Filtre las filas con la máscara ventas['categoria'] == 'Electrónica'"
assert round(float(electronica["ingreso"].sum()), 1) == 3397.5, "electronica debe conservar todas las columnas"
assert n_grandes == 18, "Cuente los True de la máscara ventas['ingreso'] > 100"
assert round(float(gye_hogar), 1) == 1413.0, "Dos condiciones con & y paréntesis; después, la columna ingreso y .sum()"

## 7. Tipos de datos y regreso a NumPy

El tipo de una columna decide qué operaciones se pueden hacer con ella. `fecha` se leyó como texto: así no se puede pedir el mes ni restar dos fechas. `pd.to_datetime` la convierte en una fecha de verdad.

In [77]:
print(ventas["fecha"].dtype)                       # texto
ventas["fecha"] = pd.to_datetime(ventas["fecha"])
print(ventas["fecha"].dtype)                       # datetime64

datetime64[us]
datetime64[us]

In [78]:
print(ventas["fecha"].min(), "→", ventas["fecha"].max())
print(ventas["fecha"].dt.month.head(3).tolist())            # .dt da acceso a las partes de la fecha
print(ventas["fecha"].dt.dayofweek.head(3).tolist())        # día de la semana: 0 = lunes … 6 = domingo
print((ventas["fecha"] >= "2026-03-01").sum(), "ventas en marzo")

2026-01-02 00:00:00 → 2026-03-31 00:00:00
[1, 1, 1]
[4, 4, 5]
78 ventas en marzo

> También se puede convertir al leer el archivo: `pd.read_csv("datos/ventas_tienda.csv", parse_dates=["fecha"])`.

`astype` cambia el tipo de una columna, como en NumPy. El tipo `category` es útil para variables categóricas con pocos valores distintos.

In [81]:
print(ventas["cantidad"].astype(float).head(3).tolist())
categoria = ventas["categoria"].astype("category")
print(categoria.cat.categories.tolist())

[1.0, 1.0, 2.0]
['Alimentos', 'Electrónica', 'Hogar', 'Papelería']

**Un dato escrito con dígitos no siempre es un número.** En la sesión 3 se clasificó el número de cédula como categórico nominal: es un identificador. Si pandas lo lee como número, se pierde el cero inicial (las cédulas de las provincias 01 a 09 empiezan con 0; la de Guayas, con 09). Los números de este ejemplo son ficticios.

In [82]:
import io

texto = "cedula,nombre\n0911111111,Ana\n1722222222,Luis\n0133333333,María\n"

mal = pd.read_csv(io.StringIO(texto))                              # pandas decide: número entero
bien = pd.read_csv(io.StringIO(texto), dtype={"cedula": str})      # se indica: texto
print(mal["cedula"].tolist())
print(bien["cedula"].tolist())

[911111111, 1722222222, 133333333]
['0911111111', '1722222222', '0133333333']

**De regreso a NumPy.** `to_numpy()` devuelve los valores como array. Hará falta en la Unidad 4: los algoritmos de *clustering* reciben una matriz de números.

In [83]:
ingreso = ventas["ingreso"].to_numpy()                         # una columna → array de una dimensión
X = ventas[["cantidad", "precio_unitario"]].to_numpy()         # varias columnas numéricas → matriz
print(type(ingreso).__name__, ingreso.shape, ingreso.dtype)
print(type(X).__name__, X.shape, X.dtype)
print(ventas[["producto", "cantidad"]].to_numpy().dtype)       # tipos mezclados → object: se pierde la ventaja de NumPy

ndarray (200,) float64
ndarray (200, 2) float64
object

**Su turno 7.1.** (a) Cree la columna `mes` con el número de mes de cada venta. (b) Guarde en `ingreso_marzo` el ingreso total de marzo. (c) Guarde en `M` una matriz de NumPy con las columnas `cantidad`, `precio_unitario` e `ingreso`.

In [105]:
# TODO: reemplace los ... por su código
ventas["mes"] = ventas["fecha"].dt.month
ingreso_marzo = ventas[ventas["mes"] == 3]["ingreso"].sum()
M = ventas[["cantidad", "precio_unitario", "ingreso"]].to_numpy()
print(ingreso_marzo)

3188.9

In [106]:
assert "mes" in ventas.columns and sorted(pd.unique(ventas["mes"]).tolist()) == [1, 2, 3], "Use ventas['fecha'].dt.month"
assert round(float(ingreso_marzo), 1) == 3188.9, "Filtre con la condición ventas['mes'] == 3, elija la columna ingreso y sume"
assert isinstance(M, np.ndarray) and M.shape == (200, 3), "Seleccione las tres columnas (corchetes dobles) y use .to_numpy()"
assert round(float(M[:, 2].sum()), 1) == 7424.8, "La tercera columna de M debe ser ingreso"

## 8. Cierre: el reto del Notebook 0, tercera versión

El ingreso por categoría se ha calculado ya tres veces:

| Sesión | Herramienta | Cómo |
|---|---|---|
| 2 | Python puro | un bucle, un diccionario y dos conversiones de tipo |
| 4 | NumPy | una máscara por categoría: `ingreso[categoria == "Hogar"].sum()` |
| 5 | pandas | lo mismo con columnas con nombre; y, en una sola línea, con `groupby` |

In [107]:
for c in ventas["categoria"].unique():                                   # con lo aprendido hoy
    print(c, ventas.loc[ventas["categoria"] == c, "ingreso"].sum().round(2))

Hogar 3042.0
Electrónica 3397.5
Alimentos 791.2
Papelería 194.1

In [108]:
ventas.groupby("categoria")["ingreso"].sum()         # adelanto de la sesión 8: agrupar y resumir

categoria
Alimentos       791.2
Electrónica    3397.5
Hogar          3042.0
Papelería       194.1
Name: ingreso, dtype: float64

Son los mismos resultados del reto (Electrónica 3397.5, Hogar 3042.0, Alimentos 791.2, Papelería 194.1).

Para **guardar** una tabla se usa `to_csv`. Con `index=False` no se escribe la columna del índice.

In [109]:
ventas.to_csv("datos/ventas_con_ingreso.csv", index=False)
pd.read_csv("datos/ventas_con_ingreso.csv").head(2)

,fecha,producto,categoria,cantidad,precio_unitario,ciudad,ingreso,ingreso_neto,tipo,mes
0,2026-01-02,Sartén,Hogar,1,18.0,Quito,18.0,16.2,minorista,1
1,2026-01-02,Mouse,Electrónica,1,15.0,Machala,15.0,13.5,minorista,1

## Resumen

| Para… | Se escribe | Ejemplo |
|---|---|---|
| leer un archivo | `pd.read_csv` | `ventas = pd.read_csv("datos/ventas_tienda.csv")` |
| inspeccionar | `.head()`, `.tail()`, `.shape`, `.columns`, `.dtypes`, `.info()`, `.describe()` | `ventas.dtypes` |
| elegir una columna | `df["col"]` → Series | `ventas["ciudad"]` |
| elegir varias columnas | `df[["a", "b"]]` → DataFrame | `ventas[["producto", "ciudad"]]` |
| crear una columna | `df["nueva"] = …` | `ventas["ingreso"] = ventas["cantidad"] * ventas["precio_unitario"]` |
| elegir por posición | `df.iloc[filas, columnas]` (fin excluido) | `ventas.iloc[:5, :3]` |
| elegir por etiqueta | `df.loc[filas, columnas]` (fin incluido) | `ventas.loc[10:12, ["producto", "ciudad"]]` |
| filtrar por condición | `df[condición]`, `df.loc[condición, columnas]` | `ventas.loc[ventas["ciudad"] == "Quito", "ingreso"]` |
| combinar condiciones | `&`, `\|`, `~`, `.isin()`, `.between()` | `(ventas["ciudad"] == "Quito") & (ventas["cantidad"] >= 5)` |
| modificar con condición | `df.loc[condición, "col"] = valor` | `ventas.loc[ventas["cantidad"] >= 5, "tipo"] = "mayorista"` |
| resumir una columna | `.sum()`, `.mean()`, `.max()`, `.idxmax()`, `.value_counts()`, `.nunique()` | `ventas["ciudad"].value_counts()` |
| ordenar | `.sort_values()` | `ventas.sort_values("ingreso", ascending=False)` |
| cambiar tipos | `pd.to_datetime`, `.astype()` | `ventas["fecha"] = pd.to_datetime(ventas["fecha"])` |
| pasar a NumPy | `.to_numpy()` | `ventas[["cantidad", "ingreso"]].to_numpy()` |

### Errores frecuentes

| Síntoma | Causa | Solución |
|---|---|---|
| `KeyError: 'Ciudad'` | el nombre de la columna no existe (mayúsculas, tildes, espacios) | copiar el nombre de `df.columns` |
| `KeyError: ('producto', 'ciudad')` | varias columnas con corchetes simples | corchetes dobles: `df[["producto", "ciudad"]]` |
| `ValueError: The truth value of a Series is ambiguous` | se usó `and` u `or` | `&` y `\|`, con paréntesis en cada condición |
| Sale una fila de más (o de menos) | se confundió `loc` (fin incluido) con `iloc` (fin excluido) | etiquetas → `loc`; posiciones → `iloc` |
| `SettingWithCopyWarning` o `ChainedAssignmentError` | asignación con dos corchetes seguidos | un solo `df.loc[condición, columna] = valor` |
| Una columna numérica no se puede sumar | se leyó como texto | revisar `df.dtypes`; convertir con `astype` o al leer |
| `FileNotFoundError` | Jupyter se abrió en otra carpeta | abrir Jupyter desde `FCDIA`; revisar `os.getcwd()` |

**Ante cualquier resultado inesperado, revise primero `.shape`, `.dtypes` y `.head()`.**